version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: yarn start
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - saucectl/saucectl-run
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build