version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@2.0.0

jobs:
  test-cypress:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - start: 'yarn start'
      - saucectl/saucectl-run

workflows:
  default_workflow:
    jobs:
      - test-cypress