version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "Install saucectl"
          command: "sudo npm i -g saucectl"
      - run:
          name: "Run Cypress Test on Sauce"
          command: "saucectl run"
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build