version: '2.1'
orbs:
  saucectl: saucelabs/saucectl-run@1.1.0
jobs:
  run_saucectl:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - saucectl/saucectl-run
workflows:
  test_on_sauce:
    jobs:
      - run_saucectl