version: 2.1
jobs:
#  build:
#    docker:
#      - image: cimg/node:lts
#    steps:
#      - checkout
#      - run: npm install
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            npm install
      - run:
          name: "Running Application"
          background: true
          command: |
            npm start
      - run:
          name: "Set Up Tunnel"
          background: true
          command: |
            curl https://saucelabs.com/downloads/sc-4.7.1-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            cd sc-*
            bin/sc -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY} --region ${SAUCE_REGION} --tunnel-name ${SAUCE_TUNNEL_IDENTIFIER}
      - run:
          name: "Install Sauce Labs saucectl"
          command: |
            sudo npm i -g saucectl
      - run:
          name: "Configure Sauce saucectl"
          command: |
            saucectl configure -u ${SAUCE_USERNAME} -a ${SAUCE_ACCESS_KEY}
      - run:
          name: "Run Cypress on Sauce"
          command: |
            saucectl run --tunnel-name ${SAUCE_TUNNEL_IDENTIFIER}
workflows:
  build_and_test:
    jobs:
      - test