version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build