version: 2.1
orbs:
  saucectl: saucelabs/saucectl-run@2.0.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Run App
          background: true
          command: |
            npm install
      - run:
          name: Install Sauce Labs and Set Up Tunnel
          background: true
          command: |
            curl https://saucelabs.com/downloads/sc-4.7.1-linux.tar.gz -o saucelabs.tar.gz
            tar -xzf saucelabs.tar.gz
            cd sc-*
            bin/sc -u ${SAUCE_USERNAME} -k ${SAUCE_ACCESS_KEY} --region ${SAUCE_REGION} --tunnel-name ${SAUCE_TUNNEL_IDENTIFIER}
      - saucectl/saucectl-run
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build