version: 2.1
apiVersion: v1alpha
kind: cypress
showConsoleLog: true
sauce:
  region: eu-central-1
  concurrency: 2
  sauceignore: .sauceignore
defaults:
  mode: sauce
  timeout: 1m
rootDir: ./
cypress:
  version: 9.1.0
  configFile: "cypress.json"
suites:
  - name: "Main Cypress Test"
    browser: "chrome"
    browserVersion: 95
    platformName: "Windows 10"
    screenResolution: "1920x1080"
    config:
      testFiles: [ "**/*.*" ]
artifacts:
  download:
    when: always
    match:
      - console.log
    directory: ./artifacts/