apiVersion: v1alpha
kind: cypress
showconsolelog: false
rootDir: ./
defaults: {}
#  mode: docker
sauce:
  region: eu-central-1
  tunnel:
    name: oauth-aleksandrs.chikinovs-f21ff_tunnel_name
  concurrency: 2
  sauceignore: .sauceignore
  metadata:
    name: Testing Cypress Support
    tags:
    - e2e
    - release team
    - other tag
    build: Cypress Sample Test Build – $DATE
  # tunnel:
  #   id: walkerlj0_tunnel_id
cypress:
  configFile: cypress.json
  version: 9.1.0
  record: false
  key: ""
suites:
- name: login test
  browser: chrome
  config:
    testFiles:
    - '**/login.spec.js'
#docker:
#  fileTransfer: mount
artifacts:
  download:
    match:
      - '*'
    when: always
    directory: ./artifacts